[package]
name = "py_maplib"
version = "0.4.8"
edition = "2021"

[workspace]

[dependencies]
pyo3 = {version = "0.19.2", features = ["extension-module"]}
maplib = {path="../maplib"}
triplestore = {path="../triplestore"}

oxrdf = "0.1.0"
arrow_python_utils = {path="../arrow_python_utils"}
thiserror="1.0.31"
polars-core = {version="0.31.1", features=["dtype-array", "dtype-categorical", "dtype-date", "dtype-datetime",
    "dtype-decimal", "dtype-duration", "dtype-i8", "dtype-i16", "dtype-struct", "dtype-time", "dtype-u8", "dtype-u16"]}

[lib]
name = "maplib"
crate-type = ["cdylib"]

[package.metadata.maturin]
python-source = "python"